# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  token: ${{ secrets.VDSINA_TOKEN }}
jobs:
  selectel: 
    runs-on: ubuntu-latest
    #secrets: {{ github.secrets.SELECTEL_TOKEN }}
    container: node
  vdsina:
    name: VDSina
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [18.x]
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: latest
       
    - run: yarn install
    - run: echo "Yarn action"
    # - run: npm run build --if-present
    # - run: npm test
    - name: Update
    - run: apk
    
      
# You may pin to the exact commit or the version.
# uses: JamsRepos/SFTP-Deploy-Action@c2ecced9e4b9c0094ad26bad07711ea12051ee21
      # uses: JamsRepos/SFTP-Deploy-Action@v2.1
      # with:
      # # Set this to your SFTP Username.
      # username: # default is root
      # # Set this to your SFTP Server IP.
      # server: 
      # # Set this to your SFTP Port, default is 22.
      # port: # default is 22
      # # Set this to your SFTP Port.
      # ssh_password: 
      # # Set this to the path to transfer from.
      # local_path: # default is ./*
      # # Set this to the path to transfer to.
      # remote_path: # default is /
      # # Set this to any optional SFTP arguments.
      # args: # optional
      # # Set this to any SSH commands you wish to run upon completion.
      # ssh_command: # optional
      # # Set this to true if you wish to upload an archive, default is false.
      # compress: # optional
  
